version: 0.2

phases:
  build:
    commands:
      - echo "Build phase"
      - mvn clean package


  test:
    commands:
      - echo "Test phase"
      - mvn test
      - echo "Unit tests passed"

  post_build:
    commands:
      - echo "Deploying..."
      - echo "Deployment complete!"

artifacts:
  files:
    - target/server.jar
  discard-paths: yes
