# the version of the build spec
version: 0.2


# In the build phase, we are using Maven to build the project
# In the post_build phase, we are echoing a message to indicate that the build has completed
phases:
  build:
    commands:
      - echo "Build phase"
      - mvn clean package

  test:
  commands:
    - echo "Test phase"
    - mvn test # Run your unit tests with Maven
    - echo "Unit tests passed" # if the tests pass, proceed to deployment
  post_success:
    - echo "Deploying..." # Proceed to deployment if tests pass
  deploy:
    commands:
      - echo "Deploying to local server..."
      - cp target/server.jar /path/to/deployment/directory
      - echo "Deployment complete!"

# Here i just give my jar file a name and discard the paths
# I chnge the name of the jar file to server.jar in pom.xml file
#so that I can easily reference it here
artifacts:
  files:
    - target/server.jar
  discard-paths: yes