version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - echo "Build phase"
      - mvn clean package

  post_build:
    commands:
      - echo "Test phase"
      - mvn test
      - echo "Unit tests passed"
      - echo "Deploying..."
      - echo "Deployment complete!"

artifacts:
  files:
    - target/server.jar
  discard-paths: yes
